{% set version = "0.4.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-downlit
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/downlit_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/downlit/downlit_{{ version }}.tar.gz
  sha256: 6c0fbe98ece8a511973263f8e8a35574df0cfc45edea7452b53b8d326436b3bd

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-brio
    - r-desc
    - r-digest
    - r-evaluate
    - r-fansi
    - r-memoise
    - r-rlang
    - r-vctrs
    - r-withr
    - r-yaml
  run:
    - r-base
    - r-brio
    - r-desc
    - r-digest
    - r-evaluate
    - r-fansi
    - r-memoise
    - r-rlang
    - r-vctrs
    - r-withr
    - r-yaml

test:
  commands:
    - $R -e "library('downlit')"           # [not win]
    - "\"%R%\" -e \"library('downlit')\""  # [win]

about:
  home: https://downlit.r-lib.org/, https://github.com/r-lib/downlit
  license: MIT
  summary: Syntax highlighting of R code, specifically designed for the needs of 'RMarkdown' packages like 'pkgdown', 'hugodown', and 'bookdown'. It includes linking of function calls to their documentation on the web, and automatic translation of ANSI escapes in output to the equivalent HTML.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: downlit
# Title: Syntax Highlighting and Automatic Linking
# Version: 0.4.0
# Authors@R: c( person("Hadley", "Wickham", , "hadley@rstudio.com", role = c("aut", "cre")), person("RStudio", role = "cph") )
# Description: Syntax highlighting of R code, specifically designed for the needs of 'RMarkdown' packages like 'pkgdown', 'hugodown', and 'bookdown'. It includes linking of function calls to their documentation on the web, and automatic translation of ANSI escapes in output to the equivalent HTML.
# License: MIT + file LICENSE
# URL: https://downlit.r-lib.org/, https://github.com/r-lib/downlit
# BugReports: https://github.com/r-lib/downlit/issues
# Depends: R (>= 3.4.0)
# Imports: brio, desc, digest, evaluate, fansi, memoise, rlang, vctrs, yaml
# Suggests: covr, htmltools, jsonlite, leaflet, MASS, pkgload, rmarkdown, testthat (>= 3.0.0), xml2
# Config/testthat/edition: 3
# Encoding: UTF-8
# RoxygenNote: 7.1.2
# NeedsCompilation: no
# Packaged: 2021-10-29 18:02:03 UTC; hadley
# Author: Hadley Wickham [aut, cre], RStudio [cph]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2021-10-29 19:40:08 UTC
